services:
  rl_main:
    build:
      context: .
      dockerfile: Dockerfile
    image: tedwang2/rl_main:0.2.0
    container_name: rl_main
    privileged: true
    tty: true
    stdin_open: true
    stop_grace_period: 1s
    network_mode: host
    working_dir: /home/ted/rl_main
    environment:
      - ROS_DOMAIN_ID=25
      - DISPLAY=${DISPLAY:-:0}
      - ROS_WS=/home/ted/rl_main/deploy
      - GROOT_APPIMAGE=/home/ted/rl_main/groot/groot.AppImage
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - QT_X11_NO_MITSHM=1 # Fix for Qt applications in Docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./entrypoint.sh:/entrypoint.sh:ro
      - /usr/lib/wsl:/usr/lib/wsl:ro
      - ../:/home/ted/rl_main
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/dxg:/dev/dxg"
    group_add:
      - "990"
    command: /bin/bash