main_node:
  ros__parameters:
    goal_areas:
      collect_0:
        side: 'east'
        pose: [0.45, 1.2]
        center: [0.3, 0.5]
      collect_1:
        side: 'west'
        pose: [2.55, 1.2]
        center: [0.4, 0.2]
      collect_2:
        north: [1.15, 1.075]
        south: [1.15, 0.525]
        center: [0.3, 0.5]
      collect_3:
        north: [1.85, 1.075]
        south: [1.85, 0.525]
        center: [0.4, 0.2]
      collect_4:
        side: 'east'
        pose: [0.45, 0.4]
        center: [0.3, 0.5]
      collect_5:
        side: 'west'
        pose: [2.55, 0.4]
        center: [0.4, 0.2]
      collect_6:
        side: 'north'
        pose: [1.1, 0.45]
        center: [0.3, 0.5]
      collect_7:
        side: 'north'
        pose: [1.9, 0.45]
        center: [0.4, 0.2]
      pantry_0:
        side: 'south'
        pose: [1.25, 1.15]
        center: [1.25, 1.45]
      pantry_1:
        side: 'south'
        pose: [1.75, 1.15]
        center: [1.75, 1.45]
      pantry_2:
        side: 'east'
        pose: [0.4, 0.8]
        center: [0.1, 0.8]
      pantry_3:
        north: [0.8, 1.1]
        south: [0.8, 0.5]
        east: [1.1, 0.8]
        west: [0.5, 0.8]
        center: [0.8, 0.8]
      pantry_4:
        north: [1.5, 1.1]
        south: [1.5, 0.5]
        east: [1.8, 0.8]
        west: [1.2, 0.8]
        center: [1.5, 0.8]
      pantry_5:
        north: [2.2, 1.1]
        south: [2.2, 0.5]
        east: [2.5, 0.8]
        west: [1.9, 0.8]
        center: [2.2, 0.8]
      pantry_6:
        side: 'west'
        pose: [2.6, 0.8]
        center: [2.9, 0.8]
      pantry_7:
        side: 'north'
        pose: [0.7, 0.4]
        center: [0.7, 0.1]
      pantry_8:
        side: 'north'
        pose: [1.5, 0.4]
        center: [1.5, 0.1]
      pantry_9:
        side: 'north'
        pose: [2.3, 0.4]
        center: [2.3, 0.1]